# keep the keys alphabetically ordered

default_epsg = 21781
max_features = 201

[db]
# Available types: postgresql, sqlite. If types doesn't match anything in this
# list, postgresql will be assumed.
# Keys below are for postgresql.
# For sqlite databases, valid keys are (in addition to type): file_path and staging.
type = 'postgresql'
name = 'geo'
host = 'geo_api3:geo_api3@db.geoportal.prod'
port = 5432
staging = 'prod'


[feedback]
default_recipient = 'support@geoportal.prod'
default_subject = 'Geoportal Customer feedback'
mail_host_name = 'localhost'
mail_host_port = 25


[raster]
available = ['MNT50']
# bt files located in data/bt
dtm_base_path = '/var/geo-api3/data'
preloaded = ['MNT50']


[search]
host = 'localhost'
port = 9312


[search.origins_to_ranks]
# This part need to be in sync in customer-infra/config/_common.dist.toml
#communes = 10


[shortener]
allowed_domains = ['geoportal.local', 'geoportal.prod']
allowed_hosts = ['localhost']


[storage]
kml = '/var/tmp'


[tests]
layer_id = 'test'


[uwsgi]
# beta work in progress
chmod = 666
chown = 'uwsgi:uwsgi'
gid = 'uwsgi'
uid = 'uwsgi'
home = ''
master = 1
processes = 4
python_path = ['.venv/lib/python3.5/site-packages', '/usr/lib64/python3.5/site-packages', '/home/jenselme/Work/geo-api3']
socket = '/run/uwsgi/geo-api3.sock'


[waitress]
# Configuration for the waitress webserver used by pserve. You must choose the ip and the port it
# must listen to.
ip = '127.0.0.1'
port = 9000


[wsgi]
modwsgi_user = 'wwwrun'
wsgi_threads = 32
